arch: TransNuSeg
batch_size: 8
dataset: test
deep_supervision: false
early_stopping: -1
epochs: 100
factor: 0.1
patch_size: 4
gamma: 0.6666666666666666
img_ext: .png
input_channels: 3
input_h: 96
input_w: 96
loss: BCEDiceLoss
lr: 0.001
mask_ext: .png
milestones: 1,2
min_lr: 1.0e-05
momentum: 0.9
name: dsb2018_96_NestedUNet_woDS
nesterov: false
num_classes: 1
num_workers: 0
optimizer: SGD
patience: 2
scheduler: CosineAnnealingLR
weight_decay: 0.0001
